### ISSUE TITLE
Directly refrencing classes loaded from ByteClassLoader

### ISSUE THREAD

**Issue by MOMIN5** [micwan88/helperclass4j#1]
So, if a jar which has a class named com.myname.MyClass is loaded, is it possible to refrence that class in project directly? (after loading it from ByteClassLoader.loadClass()), like this

`public static void main(String[] args) {
    MyClass.method()
 }`
 
 (The class is not in the project but loaded from the jar using ByteClassLoader, the jar is downloaded from internet using some sort of authentication)

 I tried it and it seems to be giving ClassNotFoundException

**Comment by micwan88** [comment]
If the class is not included by the project, you probably will get class not found while you compile it as the compiler didn't know what is "MyClass". 

The only way to use "MyClass" is by using 

(1) java reflection and you can see the example from ByteClassLoader Unit Test Case here:
https://github.com/micwan88/helperclass4j/blob/master/src/test/java/io/github/micwan88/helperclass4j/TestByteClassLoader.java
or this  
https://github.com/micwan88/helperclass4j/blob/master/src/main/java/io/github/micwan88/helperclass4j/DynamicAppLoader.java

(2) common interface (i.e. MyClass is implement a interface and that interface is included in the project), but I haven't try it

**Comment by MOMIN5** [comment]
im sorry for being late, but it isnt a compile error, the project is compiled using gradle tasks, which prevents some packages to get compiled into the jar 
`task loaderJar(type: Jar, dependsOn: shadowJar) {
	from(zipTree(shadowJar.archivePath)) {
		exclude "com/myname/**"
	}
	baseName = ""
	version = ""
	classifier = "loader"
	manifest = jar.manifest
}`

but when i run the jar, it throws ClassNotFoundException

**Comment by MOMIN5** [comment]
im sorry but i really need it @micwan88
